runtime: python39

instance_class: F2

env_variables:
  MONGO_URI: "mongodb+srv://admin:test@cluster0.2pkodqh.mongodb.net/Todo"

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
